In [3]:
import numpy as np
# create a 1D array using numpy
# arr:-  []
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))# type of the array
print(arr.shape)# shape of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
# Reshape the array
arr = arr.reshape(1, 5 ) # 1 row and 5 columns
print(arr)

[[1 2 3 4 5]]


In [7]:
arr1=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])# 2D array
print(arr1)
print(arr1.shape)# shape of the array


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [11]:
np.arange(0, 10, 2).reshape(5,1)# create an array with values from 0 to 10 with step 2

array([[0],
       [2],
       [4],
       [6],
       [8]])