In [5]:
import numpy as np
# create a 1D array using numpy
# arr:-  []
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))# type of the array
print(arr.shape)# shape of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
# Reshape the array
arr = arr.reshape(1, 5 ) # 1 row and 5 columns
print(arr)

[[1 2 3 4 5]]


In [7]:
arr1=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])# 2D array
print(arr1)
print(arr1.shape)# shape of the array


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [11]:

np.arange(0, 10, 2).reshape(5,1)# create an array with values from 0 to 10 with step 2

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3, 3))# create an array of ones
# 3 rows and 3 columns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3)# create an identity matrix of 3x3
print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
arr = np.array([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])
print(arr)
print(arr.shape)
print(arr[0, 1])# access the element at 0th row and 1st column
print(arr[0, :])# access the 0th row
print(arr[:, 1])# access the 1st column






TypeError: Field elements must be 2- or 3-tuples, got '6'

In [15]:
# n dimensional array
# Attributes of n-dimensional array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr.shape)
print(arr[0, 1, 2])# access the element at 0th row, 1st column and 2nd depth
print("Number of dimensions: ", arr.ndim)# number of dimensions
print("Number of elements: ", arr.size)# number of elements
print("Data type of the elements: ", arr.dtype)# data type of the elements
print("Size of each element in bytes: ", arr.itemsize)# size of each element in bytes
print("Total size of the array in bytes: ", arr.nbytes)# total size of the array in bytes

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
6
Number of dimensions:  3
Number of elements:  12
Data type of the elements:  int64
Size of each element in bytes:  8
Total size of the array in bytes:  96


In [16]:
# create an array of random values
arr = np.random.rand(2, 2)
print(arr)

[[0.99186436 0.50502023]
 [0.08700911 0.30315996]]


In [ ]:
# create an array of random integers
arr = np.random.randint(0, 10, (2, 2))
print(arr)

In [ ]:
# create an array of random values with a specific mean and standard deviation
arr = np.random.normal(0, 1, (2, 2))
print(arr)

In [17]:
# Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5 ])
arr2 = np.array([10,20,30,40,50])

# Elementwise addition
print("Add",arr1 + arr2)

# Elementwise subtraction
print("Subtract",arr1 - arr2)

# Elementwise multiplication
print("Multiply",arr1 * arr2)

# Elementwise division
print("Divide",arr1 / arr2)


Add [ 7  9 11 13 15]
Subtract [-5 -5 -5 -5 -5]
Multiply [ 6 14 24 36 50]
Divide [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [10]:
## Universal Function

arr = np.array([1, 4, 9, 16, 25])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1. 2. 3. 4. 5.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [13]:
# array slicing and indexing
arr = np.array([[1,2,3],[4,5,6],[9,10,11]])
# print("Array : \n", arr)
print(arr[1:,1:3])

[[ 5  6]
 [10 11]]


In [14]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3]
 [6]]
